package com.jswl.portal.entity;

public class Column {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_column.id
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_column.code
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_column.name
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_column.pid
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_column.sort
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_column.status
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_column.type
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_column.style
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    private String style;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column.id
     *
     * @return the value of t_column.id
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column.id
     *
     * @param id the value for t_column.id
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column.code
     *
     * @return the value of t_column.code
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column.code
     *
     * @param code the value for t_column.code
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column.name
     *
     * @return the value of t_column.name
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column.name
     *
     * @param name the value for t_column.name
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column.pid
     *
     * @return the value of t_column.pid
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column.pid
     *
     * @param pid the value for t_column.pid
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column.sort
     *
     * @return the value of t_column.sort
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column.sort
     *
     * @param sort the value for t_column.sort
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

   

    public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column.style
     *
     * @return the value of t_column.style
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public String getStyle() {
        return style;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column.style
     *
     * @param style the value for t_column.style
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public void setStyle(String style) {
        this.style = style == null ? null : style.trim();
    }

	@Override
	public String toString() {
		return "Column [id=" + id + ", code=" + code + ", name=" + name + ", pid=" + pid + ", sort=" + sort
				+ ", status=" + status + ", type=" + type + ", style=" + style + "]";
	}
    
    
    
    
    
}