package com.jswl.portal.entity;

public class Image {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_image.id
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_image.title
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_image.type
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_image.url
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_image.sort
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_image.href
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    private String href;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_image.id
     *
     * @return the value of t_image.id
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_image.id
     *
     * @param id the value for t_image.id
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_image.title
     *
     * @return the value of t_image.title
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_image.title
     *
     * @param title the value for t_image.title
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_image.type
     *
     * @return the value of t_image.type
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_image.type
     *
     * @param type the value for t_image.type
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_image.url
     *
     * @return the value of t_image.url
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_image.url
     *
     * @param url the value for t_image.url
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_image.sort
     *
     * @return the value of t_image.sort
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_image.sort
     *
     * @param sort the value for t_image.sort
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_image.href
     *
     * @return the value of t_image.href
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public String getHref() {
        return href;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_image.href
     *
     * @param href the value for t_image.href
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public void setHref(String href) {
        this.href = href == null ? null : href.trim();
    }

	@Override
	public String toString() {
		return "Image [id=" + id + ", title=" + title + ", type=" + type + ", url=" + url + ", sort=" + sort + ", href="
				+ href + "]";
	}
    
    
    
}