package com.jswl.portal.entity;

public class Menu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_menu.id
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_menu.name
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_menu.url
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_menu.type
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    private Boolean type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_menu.pid
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_menu.sort
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_menu.icon
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_menu.status
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    private Boolean status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_menu.id
     *
     * @return the value of s_menu.id
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_menu.id
     *
     * @param id the value for s_menu.id
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_menu.name
     *
     * @return the value of s_menu.name
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_menu.name
     *
     * @param name the value for s_menu.name
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_menu.url
     *
     * @return the value of s_menu.url
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_menu.url
     *
     * @param url the value for s_menu.url
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_menu.type
     *
     * @return the value of s_menu.type
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public Boolean getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_menu.type
     *
     * @param type the value for s_menu.type
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public void setType(Boolean type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_menu.pid
     *
     * @return the value of s_menu.pid
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_menu.pid
     *
     * @param pid the value for s_menu.pid
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_menu.sort
     *
     * @return the value of s_menu.sort
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_menu.sort
     *
     * @param sort the value for s_menu.sort
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_menu.icon
     *
     * @return the value of s_menu.icon
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_menu.icon
     *
     * @param icon the value for s_menu.icon
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_menu.status
     *
     * @return the value of s_menu.status
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_menu.status
     *
     * @param status the value for s_menu.status
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }
}