package com.jswl.portal.entity;

public class RoleAndMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_role_menu.id
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_role_menu.role_id
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_role_menu.menu_id
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    private Integer menuId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_role_menu.id
     *
     * @return the value of s_role_menu.id
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_role_menu.id
     *
     * @param id the value for s_role_menu.id
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_role_menu.role_id
     *
     * @return the value of s_role_menu.role_id
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_role_menu.role_id
     *
     * @param roleId the value for s_role_menu.role_id
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_role_menu.menu_id
     *
     * @return the value of s_role_menu.menu_id
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_role_menu.menu_id
     *
     * @param menuId the value for s_role_menu.menu_id
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }
}