package com.jswl.portal.entity;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.id
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.user_code
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    private String userCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.password
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.user_type
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    private Boolean userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.status
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.user_name
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.english_name
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    private String englishName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.sex
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    private Boolean sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.post
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    private String post;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.hiredate
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    private Long hiredate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.contact_number
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    private String contactNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.phone_number
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.email
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.education
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    private Byte education;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.birthday
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.remarks
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.create_time
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.create_user_id
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.modify_time
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    private Long modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.modify_user_id
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    private Long modifyUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.id
     *
     * @return the value of s_user.id
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.id
     *
     * @param id the value for s_user.id
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.user_code
     *
     * @return the value of s_user.user_code
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.user_code
     *
     * @param userCode the value for s_user.user_code
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.password
     *
     * @return the value of s_user.password
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.password
     *
     * @param password the value for s_user.password
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.user_type
     *
     * @return the value of s_user.user_type
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public Boolean getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.user_type
     *
     * @param userType the value for s_user.user_type
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public void setUserType(Boolean userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.status
     *
     * @return the value of s_user.status
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.status
     *
     * @param status the value for s_user.status
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.user_name
     *
     * @return the value of s_user.user_name
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.user_name
     *
     * @param userName the value for s_user.user_name
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.english_name
     *
     * @return the value of s_user.english_name
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public String getEnglishName() {
        return englishName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.english_name
     *
     * @param englishName the value for s_user.english_name
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public void setEnglishName(String englishName) {
        this.englishName = englishName == null ? null : englishName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.sex
     *
     * @return the value of s_user.sex
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public Boolean getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.sex
     *
     * @param sex the value for s_user.sex
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public void setSex(Boolean sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.post
     *
     * @return the value of s_user.post
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public String getPost() {
        return post;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.post
     *
     * @param post the value for s_user.post
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public void setPost(String post) {
        this.post = post == null ? null : post.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.hiredate
     *
     * @return the value of s_user.hiredate
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public Long getHiredate() {
        return hiredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.hiredate
     *
     * @param hiredate the value for s_user.hiredate
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public void setHiredate(Long hiredate) {
        this.hiredate = hiredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.contact_number
     *
     * @return the value of s_user.contact_number
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public String getContactNumber() {
        return contactNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.contact_number
     *
     * @param contactNumber the value for s_user.contact_number
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public void setContactNumber(String contactNumber) {
        this.contactNumber = contactNumber == null ? null : contactNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.phone_number
     *
     * @return the value of s_user.phone_number
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.phone_number
     *
     * @param phoneNumber the value for s_user.phone_number
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.email
     *
     * @return the value of s_user.email
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.email
     *
     * @param email the value for s_user.email
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.education
     *
     * @return the value of s_user.education
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public Byte getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.education
     *
     * @param education the value for s_user.education
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public void setEducation(Byte education) {
        this.education = education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.birthday
     *
     * @return the value of s_user.birthday
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.birthday
     *
     * @param birthday the value for s_user.birthday
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.remarks
     *
     * @return the value of s_user.remarks
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.remarks
     *
     * @param remarks the value for s_user.remarks
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.create_time
     *
     * @return the value of s_user.create_time
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.create_time
     *
     * @param createTime the value for s_user.create_time
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.create_user_id
     *
     * @return the value of s_user.create_user_id
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.create_user_id
     *
     * @param createUserId the value for s_user.create_user_id
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.modify_time
     *
     * @return the value of s_user.modify_time
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public Long getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.modify_time
     *
     * @param modifyTime the value for s_user.modify_time
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public void setModifyTime(Long modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.modify_user_id
     *
     * @return the value of s_user.modify_user_id
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public Long getModifyUserId() {
        return modifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.modify_user_id
     *
     * @param modifyUserId the value for s_user.modify_user_id
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    public void setModifyUserId(Long modifyUserId) {
        this.modifyUserId = modifyUserId;
    }

	@Override
	public String toString() {
		return "User [id=" + id + ", userCode=" + userCode + ", password=" + password + ", userType=" + userType
				+ ", status=" + status + ", userName=" + userName + ", englishName=" + englishName + ", sex=" + sex
				+ ", post=" + post + ", hiredate=" + hiredate + ", contactNumber=" + contactNumber + ", phoneNumber="
				+ phoneNumber + ", email=" + email + ", education=" + education + ", birthday=" + birthday
				+ ", remarks=" + remarks + ", createTime=" + createTime + ", createUserId=" + createUserId
				+ ", modifyTime=" + modifyTime + ", modifyUserId=" + modifyUserId + "]";
	}
    
}