package com.jswl.portal.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import com.jswl.portal.dto.ArticleDto;
import com.jswl.portal.entity.Article;
import com.jswl.portal.entity.ArticleExample;

public interface ArticleMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_article
	 *
	 * @mbggenerated Wed Sep 18 16:17:34 CST 2019
	 */
	int countByExample(ArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_article
	 *
	 * @mbggenerated Wed Sep 18 16:17:34 CST 2019
	 */
	int deleteByExample(ArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_article
	 *
	 * @mbggenerated Wed Sep 18 16:17:34 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_article
	 *
	 * @mbggenerated Wed Sep 18 16:17:34 CST 2019
	 */
	int insert(Article record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_article
	 *
	 * @mbggenerated Wed Sep 18 16:17:34 CST 2019
	 */
	int insertSelective(Article record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_article
	 *
	 * @mbggenerated Wed Sep 18 16:17:34 CST 2019
	 */
	List<Article> selectByExampleWithBLOBs(ArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_article
	 *
	 * @mbggenerated Wed Sep 18 16:17:34 CST 2019
	 */
	List<Article> selectByExample(ArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_article
	 *
	 * @mbggenerated Wed Sep 18 16:17:34 CST 2019
	 */
	Article selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_article
	 *
	 * @mbggenerated Wed Sep 18 16:17:34 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Article record, @Param("example") ArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_article
	 *
	 * @mbggenerated Wed Sep 18 16:17:34 CST 2019
	 */
	int updateByExampleWithBLOBs(@Param("record") Article record, @Param("example") ArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_article
	 *
	 * @mbggenerated Wed Sep 18 16:17:34 CST 2019
	 */
	int updateByExample(@Param("record") Article record, @Param("example") ArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_article
	 *
	 * @mbggenerated Wed Sep 18 16:17:34 CST 2019
	 */
	int updateByPrimaryKeySelective(Article record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_article
	 *
	 * @mbggenerated Wed Sep 18 16:17:34 CST 2019
	 */
	int updateByPrimaryKeyWithBLOBs(Article record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_article
	 *
	 * @mbggenerated Wed Sep 18 16:17:34 CST 2019
	 */
	int updateByPrimaryKey(Article record);

	/**
	 * 查询文章集合的方法
	 * @param columnId 栏目的id
	 * @param num  查多少条
	 * @return
	 */
	 List<Article> findArticles(@Param("columnId")Integer columnId,@Param("num")Integer num);
	
	 //跳转上一页
	Article beforeAsThisPage(ArticleDto articleDto);
	 //跳转下一页
	Article afterAsThisPage(ArticleDto articleDto);
	
	//文章管理页面展示
	List<ArticleDto> findAllArticleDtos();
	
	
	
	
	
	
	
	
	
	
	
}











