package com.jswl.portal.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.jswl.portal.entity.Column;
import com.jswl.portal.entity.ColumnExample;

public interface ColumnMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_column
	 *
	 * @mbggenerated Wed Sep 18 16:17:34 CST 2019
	 */
	int countByExample(ColumnExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_column
	 *
	 * @mbggenerated Wed Sep 18 16:17:34 CST 2019
	 */
	int deleteByExample(ColumnExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_column
	 *
	 * @mbggenerated Wed Sep 18 16:17:34 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_column
	 *
	 * @mbggenerated Wed Sep 18 16:17:34 CST 2019
	 */
	int insert(Column record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_column
	 *
	 * @mbggenerated Wed Sep 18 16:17:34 CST 2019
	 */
	int insertSelective(Column record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_column
	 *
	 * @mbggenerated Wed Sep 18 16:17:34 CST 2019
	 */
	List<Column> selectByExample(ColumnExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_column
	 *
	 * @mbggenerated Wed Sep 18 16:17:34 CST 2019
	 */
	Column selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_column
	 *
	 * @mbggenerated Wed Sep 18 16:17:34 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Column record, @Param("example") ColumnExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_column
	 *
	 * @mbggenerated Wed Sep 18 16:17:34 CST 2019
	 */
	int updateByExample(@Param("record") Column record, @Param("example") ColumnExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_column
	 *
	 * @mbggenerated Wed Sep 18 16:17:34 CST 2019
	 */
	int updateByPrimaryKeySelective(Column record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_column
	 *
	 * @mbggenerated Wed Sep 18 16:17:34 CST 2019
	 */
	int updateByPrimaryKey(Column record);

	
	
	

}