package com.jswl.portal.dao;

import com.jswl.portal.entity.RoleAndMenu;
import com.jswl.portal.entity.RoleAndMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleAndMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role_menu
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    int countByExample(RoleAndMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role_menu
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    int deleteByExample(RoleAndMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role_menu
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role_menu
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    int insert(RoleAndMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role_menu
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    int insertSelective(RoleAndMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role_menu
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    List<RoleAndMenu> selectByExample(RoleAndMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role_menu
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    RoleAndMenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role_menu
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    int updateByExampleSelective(@Param("record") RoleAndMenu record, @Param("example") RoleAndMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role_menu
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    int updateByExample(@Param("record") RoleAndMenu record, @Param("example") RoleAndMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role_menu
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    int updateByPrimaryKeySelective(RoleAndMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role_menu
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    int updateByPrimaryKey(RoleAndMenu record);
}