package com.jswl.portal.dao;

import com.jswl.portal.entity.UserAndAuth;
import com.jswl.portal.entity.UserAndAuthExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserAndAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_auth
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    int countByExample(UserAndAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_auth
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    int deleteByExample(UserAndAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_auth
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_auth
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    int insert(UserAndAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_auth
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    int insertSelective(UserAndAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_auth
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    List<UserAndAuth> selectByExample(UserAndAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_auth
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    UserAndAuth selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_auth
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserAndAuth record, @Param("example") UserAndAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_auth
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    int updateByExample(@Param("record") UserAndAuth record, @Param("example") UserAndAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_auth
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    int updateByPrimaryKeySelective(UserAndAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_auth
     *
     * @mbggenerated Wed Sep 18 16:17:34 CST 2019
     */
    int updateByPrimaryKey(UserAndAuth record);
}